# Welcome to Harmoniza!

# Site settings
title: Harmoniza
email: el602444@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Harmoniza is your go-to source for high-quality, royalty-free music and audio resources. 
  We provide loops, chord progressions, sound effects, vocals, and full tracks designed to elevate your projects. 
  Our mission is to make professional music production tools accessible to all creators.
baseurl: "harmoniza" # the subpath of your site, e.g. /blog
url: "https://harmoniza.github.io/harmoniza/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Harmoniza

# Social links
bandlab_url: https://www.bandlab.com/harmoniza_
bandcamp_url: https://harmoniza.bandcamp.com/
youtube_url: https://www.youtube.com/@Harmoniza7

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Permalinks for blog posts
permalink: /blog/:title/
# Exclude from processing
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
