# Welcome to Harmoniza!

# Site settings
title: Harmoniza
email: el602444@gmail.com
description: >-
  Explore high-quality, royalty-free music tracks and resources designed to elevate your creative projects. At Harmoniza, you have the freedom to pay what you want for the music that inspires you.
baseurl: "/harmoniza" # Set to /harmoniza when deploying to GitHub Pages
url: "https://harmoniza.github.io/harmoniza/" # Update to https://harmoniza.github.io/harmoniza/ when deploying
github_username: Harmoniza

# Social links
bandlab_url: https://www.bandlab.com/harmoniza_
bandcamp_url: https://harmoniza.bandcamp.com/
youtube_url: https://www.youtube.com/@Harmoniza7

# Theme and SEO
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

# Theme customizations (supported by minima)
minima:
  skin: dark
  social_links: true
  navigation:
    - title: "Home"
      url: /
    - title: "About"
      url: /about/
    - title: "Music"
      url: /music/
    - title: "Resources"
      url: /tools_and_resources/
    - title: "Blog"
      url: /blog/

# Permalinks
permalink: /blog/:title/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Google Analytics (if using)
google_analytics: "UA-XXXXX-Y"
