# Welcome to Harmoniza!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Harmoniza
email: el602444@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Harmoniza is your go-to source for high-quality, royalty-free music and audio resources. 
  We provide loops, chord progressions, sound effects, vocals, and full tracks designed to elevate your projects. 
  Our mission is to make professional music production tools accessible to all creators.
baseurl: "/Harmoniza" # the subpath of your site, e.g. /blog
url: "https://harmoniza.github.io/harmoniza/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Harmoniza

# Social links
bandlab_url: https://www.bandlab.com/harmoniza_
bandcamp_url: https://harmoniza.bandcamp.com/
youtube_url: https://www.youtube.com/@Harmoniza7

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
