title: Harmoniza
email: el602444@gmail.com
description: >-
  Official website for Harmoniza, featuring lofi, ambient, trap, pop music, and more. Find drumbeats, chord progressions, loops, and more!
baseurl: "/harmoniza" # the subpath of your site
url: "https://harmoniza.github.io" # the base hostname & protocol for your site
twitter_username: Harmoniza
github_username: Harmoniza

# Build settings
theme: minima
plugins:
  - jekyll-feed
